### ISSUE TITLE
 I have a question for you. OTL

### ISSUE THREAD

**Issue by fpemdksk** [DavidAnson/DHCPLite#1]
I can not speak English very well. please understand.

I wonder about this source code.

When my computer runs the DCHPLite server
Can other computers on the same router receive IP through dchpLite?

**Comment by DavidAnson** [comment]
Maybe.

If all computers are connected to the same HUB, they will all exchange DHCP traffic: https://en.m.wikipedia.org/wiki/Ethernet_hub

If they are in a SWITCH, they may not because of the way DHCP packets are exchanged: https://en.m.wikipedia.org/wiki/Network_switch

The best way to know is to try. DHCPLite will show all the traffic it receives and sends, so you can tell what is going on. :)

Hope this helps!

**Comment by fpemdksk** [comment]
very thanksT_T
